### ISSUE TITLE
Has this code used online fine-tune in the default evaluation process？

### ISSUE THREAD

**Issue by STverr7** [andr345/frtm-vos#10]
Hi,thanks for your nice code.The approach in the paper is to fine-tune the target net when testing.I'd like to ask whether you did this in the evaluate.py or not? Thank you.

**Comment by andr345** [comment]
Yes, we fine-tune the target model in the evaluation too. This is controlled by the train_skipping, learning_rate and update_iters parameters in evaluate.py.
