### ISSUE TITLE
when run train.py, 'TargetObject' object has no attribute 'get_state_dict'

### ISSUE THREAD

**Issue by tinaZZer** [andr345/frtm-vos#12]
Hi, I can run evaluate.py, but run train.py faild.
```
(p36) rtm@rtm:~/zc/f/frtm-vos$ python train.py dv17_res101 --ftext resnet101 --dset dv2017 --dev cuda:0
Compiling npp extension
done
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    trainer.train()
  File "/home/rtm/zc/f/frtm-vos/lib/training.py", line 131, in train
    stats = self.model(*batch)
  File "/home/rtm/Envs/p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rtm/zc/f/frtm-vos/model/training_model.py", line 92, in forward
    cache_hits = self._initialize(images[0], labels[0], specs)
  File "/home/rtm/zc/f/frtm-vos/model/training_model.py", line 137, in _initialize
    self.save_target_model(specs[i], L, self.tmodels[i].get_state_dict())
AttributeError: 'TargetObject' object has no attribute 'get_state_dict'
```
my env:
pytohn3.6
torch1.0.1
Do you have any suggestions?
Thanks!

**Comment by andr345** [comment]
Fixed the problem. The get_state_dict() function was missing.

**Comment by tinaZZer** [comment]
@andr345  Thank you! I uncompressed the target model cache before and skipped this bug. 
But I have another problem. when running train.py , tensorboard is not activated.  Building the nppig_cpp needs torch1.0.1, while 
`from torch.utils.tensorboard import SummaryWriter `need torch>=1.1, so I replaced  torch.utils.tensorboard with tensorboardX in trainning.py . Then, the code run, but  tensorboard is not activated. Do you have sulutions to use same version? or I need to rewrite the content of tensorboardX?

**Comment by andr345** [comment]
You could try inserting tensorboard module from pytorch 1.5. That is, copy this module
https://github.com/pytorch/pytorch/tree/master/torch/utils/tensorboard
into the project and import SummarWriter from there.

Looking at the import statements, it seems fairly standalone, even from pytorch itself. There are some caffe2 dependencies, but I think you could just remove those if they cause problems.

**Comment by tinaZZer** [comment]
@andr345 Thanks for your solution！pytorch 1.5 seems inappropriate, I copy the tensorboard module of pytorch 1.1 and it works.
