### ISSUE TITLE
How to understand the discriminative model in the paper

### ISSUE THREAD

**Issue by lichuntang** [andr345/frtm-vos#21]
Hi, thanks for sharing！
The discriminative method used in the paper is called the target model, and this corresponds to the "Discriminator" class in the code. The "Discriminator" is often used in the generative adversarial networks. So how should I understand it and whether it is related to the generative adversarial networks？But from the perspective of the loss function and its model, I did not find that it is related to GAN, so why is it called "Discriminator". Looking forward to your response, thank you！

**Comment by felja633** [comment]
Yes, the Discriminator in the code corresponds to the target model in the paper. It is optimized online to discriminate target features from the background features.
