### ISSUE TITLE
About the learning objective for target model

### ISSUE THREAD

**Issue by liuziyang123** [andr345/frtm-vos#26]
Hi, tanks for your excellent work.
During reading your paper and codes, I have a question:
A L2 loss is adopted in Equation (2) as in your paper.
But in _discriminator.py_, the residual was computed by _residuals = self.w * (s - self.y)_, which dosen't seem to be a L2 loss.
Could you explain why the residual is not computed as in your paper? Or, are they equivalent to each other?
Thanks a lot.

**Comment by felja633** [comment]
The residual is computed as in the paper and is used in the quadratic equation in (3). Read further under optimization in section 3.1.

**Comment by liuziyang123** [comment]
> The residual is computed as in the paper and is used in the quadratic equation in (3). Read further under optimization in section 3.1.

Yes, I thought I figured it out. I thought the code in _optimizer.py_

_'self.dfdxt_g = TensorList(torch.autograd.grad(self.f0, self.x, self.g, create_graph=True))'_

implicitly obtains derivatives from the quadratic objective.  Am I right?
