### ISSUE TITLE
when compiling npp extension and the code dosen't work ?

### ISSUE THREAD

**Issue by qianjinhao** [andr345/frtm-vos#9]
when I run the code, it stops at compiling npp extension, and I don't know why?

**Comment by andr345** [comment]
Hi, what might be happening is that PyTorch is waiting for a lock-file to disappear.
Please check the "tmp" directory in your home directory. Is there a file named "lock" or something similar in there? If so, remove it.

**Comment by huangshenneng** [comment]
Hi,Thank you for the code .I meat the same problem when compiling npp extension.Is it work in window 10?

**Comment by andr345** [comment]
Unfortunately, I am not running pytorch on any Windows 10 computer. However, you can turn on compilation status messages to see what is happening. Go to [lib/_npp/__init__.py](https://github.com/andr345/frtm-vos/blob/master/lib/_npp/__init__.py) and set verbose=True in the load() call on line 15.

**Comment by 9p15p** [comment]
Thank you.

> Hi, what might be happening is that PyTorch is waiting for a lock-file to disappear.
> Please check the "tmp" directory in your home directory. Is there a file named "lock" or something similar in there? If so, remove it.

Thank you, sir.  I don't have this dir, but I create one like`mkdir $HOME/tmp` ,it works.

Maybe, if you're in root and don't have `/tmp` too, you should `mkdir /tmp` .  ^_^

**Comment by andr345** [comment]
I think I sorted it out. Pytorch does not create a user-provieded directory automatically, so I added this.
